Feature/flask
rombaks/ru-study-python pull request #4
Opened 2022-10-04 18:02 UTC by rombaks

Вы должны создать API для обработки CRUD запросов.

    В данной задаче все пользователи хранятся в одном словаре, где ключ - это имя пользователя,
    а значение - его параметры. {"user1": {"age": 33}, "user2": {"age": 20}}

    Словарь (dict) хранить в памяти, он должен быть пустым при старте flask.

    POST /user - создание пользователя.
    В теле запроса приходит JSON в формате {"name": <имя пользователя>}.
    Ответ должен вернуться так же в JSON в формате {"data": "User <имя пользователя> is created!"}
    со статусом 201.
    Если в теле запроса не было ключа "name", то в ответ возвращается JSON
    {"errors": {"name": "This field is required"}} со статусом 422

    GET /user/<name> - чтение пользователя
    В ответе должен вернуться JSON {"data": "My name is <name>"}. Статус 200

    PATCH /user/<name> - обновление пользователя
    В теле запроса приходит JSON в формате {"name": <new_name>}.
    В ответе должен вернуться JSON {"data": "My name is <new_name>"}. Статус 200

    DELETE /user/<name> - удаление пользователя
    В ответ должен вернуться статус 204

2022-10-05 07:05 UTC, aleksandr-semenov-dbp requested changes

2022-10-05 07:05 UTC, aleksandr-semenov-dbp commented on exercises/flask.py
> +            return make_response(message, status_code)
что если ни одно из условий if/elif не выполняется?

2022-10-05 07:33 UTC, rombaks commented on exercises/flask.py
> +            return make_response(message, status_code)
Спасибо за замечание.

Будет ошибка, т.к. не определены переменные message и status_code. 

Необходимо либо в каждое условие поместить свой return, либо в начале метода задать ответ по умолчанию.

2022-10-05 10:42 UTC, rombaks commented on exercises/flask.py
> +            return make_response(message, status_code)
> 
UPD

Попытался покрыть это вопрос тестами, но мне не удалось повторить ситауцию, при которой написанного кода было бы недостачно. 

Если делать любой запрос, в теле которого отсутствует "name",  то отрабатывает первое условие, т.е. NOT_FOUND.

Если сделать отсутсвующий в роутинге запрос (например PUT), в теле которого присутвует "name", то сервер сам выдает нужную ошибку METHOD_NOT_ALLOWED. 

Можно конечно в else возвращать заглушку в виде html(типа ссылки на домашнюю страницу), но я пока не понимаю как это протестировать.

Может я что-то упускаю?

2022-10-08 15:02 UTC, aleksandr-semenov-dbp commented on exercises/flask.py
> +            return make_response(message, status_code)
Согласен, принимается, моя ошибка, я не не заметил, что есть ограничение methods. Но, хочу отметить что мне осложнили чтение вот эти if xxx: return yyy; else/elif ... Если в тело вложеной конструкции кончается на return - не надо писать else/elif, они заставляют читающего запоминать больше контекста. Мы такое в рабчий код не пропускаем.

2022-10-09 11:43 UTC, rombaks commented on exercises/flask.py
> +            return make_response(message, status_code)
Спасибо за обратную связь. Привел к удобному для чтения виду

2022-10-09 11:43 UTC, merged